# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build for nativeTesting"
  lane :build_nativetesting do
    gradle(task: "clean assembleNativetesting")
  end

  desc "Build android release bundle"
  lane :build_release do
    gradle(task: "clean bundleRelease")
  end

  desc "Build android release bundle and install it on connected device"
  lane :build_release_install do
    gradle(task: "clean assembleRelease")
    sh("adb install -r ../app/build/outputs/apk/release/app-release.apk")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # screenshots
    # upload_to_play_store
  end
end
